### ISSUE TITLE
ui shift map open button places file path in the scaler list.

### ISSUE THREAD

**Issue by alconley** [gwm17/spsevb#1]
Fix is line 252 on app.rs file.  _Some(real_path) => self.parameters.scaler_list = Some(real_path)_  should be _Some(real_path) => self.parameters.shift_map = Some(real_path)_

Also maybe include a shift map example file.  For my stuff,

board# channel# shift#
1 0 685
1 1 685

**Comment by gwm17** [comment]
Fixed in devel, will be merged soon.
