### ISSUE TITLE
Kinematics Error

### ISSUE THREAD

**Issue by alconley** [gwm17/spsevb#5]
In kinematics.rs,

1) term1 error

fix: let term1 = (projectile.mass * ejectile.mass * params.projectile_ke).sqrt() / 
                     (ejectile.mass + residual.mass) * angle_rads.cos();

Before the numerator had ' + ' instead of ' * '

2) rho error
fix: let rho = ejectile_p /((ejectile.z as f64) * params.b_field * QBRHO2P);

before ejectile.z was target.z
Makes sense that this was the main error since when target z increased, rho essentially went to 0.  Also the target isn't going through the magnet so it need to be the ejectile!

These now will give the same results as the SPS_SABRE/CEBRA_EVENTBUILDER

**Comment by gwm17** [comment]
Done! Thanks for catching this!
